# Generated by Django 3.1.1 on 2020-09-28 19:01

import relativedeltafield
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', relativedeltafield.RelativeDeltaField(blank=True, null=True)),
            ],
        ),
    ]
