# Generated by Django 3.1.2 on 2020-10-02 14:44

import datetime
from django.db import migrations, models
import relativedeltafield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', relativedeltafield.fields.RelativeDeltaField(blank=True, null=True)),
                ('date', models.DateField(default=datetime.date(2020, 10, 21))),
            ],
        ),
    ]
