# Generated by Django 3.1.1 on 2020-09-28 22:05

from dateutil.relativedelta import relativedelta
from django.db import migrations, models
import relativedeltafield


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntervalWithChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', relativedeltafield.RelativeDeltaField(blank=True, choices=[(relativedelta(months=+1), '1 month'), (relativedelta(months=+3), '3 months'), (relativedelta(months=+6), '6 months')], null=True)),
            ],
        ),
    ]
